use std::fmt;

use card::{Card, Suit, Value};

impl fmt::Display for Card {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            Card { suit: Suit::Spade, value: Value::Two } => write!(f, "{}", '🂢'),
            Card { suit: Suit::Club, value: Value::Five } => write!(f, "{}", '🃕'),
            Card { suit: Suit::Diamond, value: Value::Eight } => write!(f, "{}", '🃈'),
            Card { suit: Suit::Spade, value: Value::Ten } => write!(f, "{}", '🂪'),
            Card { suit: Suit::Diamond, value: Value::Nine } => write!(f, "{}", '🃉'),
            Card { suit: Suit::Heart, value: Value::Three } => write!(f, "{}", '🂳'),
            Card { suit: Suit::Heart, value: Value::Ten } => write!(f, "{}", '🂺'),
            Card { suit: Suit::Spade, value: Value::Nine } => write!(f, "{}", '🂩'),
            Card { suit: Suit::Club, value: Value::King } => write!(f, "{}", '🃞'),
            Card { suit: Suit::Club, value: Value::Eight } => write!(f, "{}", '🃘'),
            Card { suit: Suit::Heart, value: Value::King } => write!(f, "{}", '🂾'),
            Card { suit: Suit::Heart, value: Value::Jack } => write!(f, "{}", '🂻'),
            Card { suit: Suit::Spade, value: Value::Three } => write!(f, "{}", '🂣'),
            Card { suit: Suit::Heart, value: Value::Five } => write!(f, "{}", '🂵'),
            Card { suit: Suit::Spade, value: Value::Ace } => write!(f, "{}", '🂡'),
            Card { suit: Suit::Spade, value: Value::Four } => write!(f, "{}", '🂤'),
            Card { suit: Suit::Heart, value: Value::Ace } => write!(f, "{}", '🂱'),
            Card { suit: Suit::Spade, value: Value::Six } => write!(f, "{}", '🂦'),
            Card { suit: Suit::Spade, value: Value::Eight } => write!(f, "{}", '🂨'),
            Card { suit: Suit::Heart, value: Value::Six } => write!(f, "{}", '🂶'),
            Card { suit: Suit::Spade, value: Value::Jack } => write!(f, "{}", '🂫'),
            Card { suit: Suit::Diamond, value: Value::Queen } => write!(f, "{}", '🃍'),
            Card { suit: Suit::Club, value: Value::Ace } => write!(f, "{}", '🃑'),
            Card { suit: Suit::Club, value: Value::Queen } => write!(f, "{}", '🃝'),
            Card { suit: Suit::Club, value: Value::Six } => write!(f, "{}", '🃖'),
            Card { suit: Suit::Diamond, value: Value::Jack } => write!(f, "{}", '🃋'),
            Card { suit: Suit::Club, value: Value::Seven } => write!(f, "{}", '🃗'),
            Card { suit: Suit::Diamond, value: Value::Six } => write!(f, "{}", '🃆'),
            Card { suit: Suit::Club, value: Value::Jack } => write!(f, "{}", '🃛'),
            Card { suit: Suit::Diamond, value: Value::Ace } => write!(f, "{}", '🃁'),
            Card { suit: Suit::Diamond, value: Value::Three } => write!(f, "{}", '🃃'),
            Card { suit: Suit::Diamond, value: Value::King } => write!(f, "{}", '🃎'),
            Card { suit: Suit::Heart, value: Value::Eight } => write!(f, "{}", '🂸'),
            Card { suit: Suit::Club, value: Value::Four } => write!(f, "{}", '🃔'),
            Card { suit: Suit::Club, value: Value::Ten } => write!(f, "{}", '🃚'),
            Card { suit: Suit::Diamond, value: Value::Five } => write!(f, "{}", '🃅'),
            Card { suit: Suit::Club, value: Value::Three } => write!(f, "{}", '🃓'),
            Card { suit: Suit::Heart, value: Value::Four } => write!(f, "{}", '🂴'),
            Card { suit: Suit::Diamond, value: Value::Ten } => write!(f, "{}", '🃊'),
            Card { suit: Suit::Diamond, value: Value::Two } => write!(f, "{}", '🃂'),
            Card { suit: Suit::Diamond, value: Value::Seven } => write!(f, "{}", '🃇'),
            Card { suit: Suit::Spade, value: Value::King } => write!(f, "{}", '🂮'),
            Card { suit: Suit::Spade, value: Value::Five } => write!(f, "{}", '🂥'),
            Card { suit: Suit::Heart, value: Value::Nine } => write!(f, "{}", '🂹'),
            Card { suit: Suit::Club, value: Value::Two } => write!(f, "{}", '🃒'),
            Card { suit: Suit::Spade, value: Value::Queen } => write!(f, "{}", '🂭'),
            Card { suit: Suit::Heart, value: Value::Queen } => write!(f, "{}", '🂽'),
            Card { suit: Suit::Heart, value: Value::Two } => write!(f, "{}", '🂲'),
            Card { suit: Suit::Diamond, value: Value::Four } => write!(f, "{}", '🃄'),
            Card { suit: Suit::Heart, value: Value::Seven } => write!(f, "{}", '🂷'),
            Card { suit: Suit::Spade, value: Value::Seven } => write!(f, "{}", '🂧'),
            Card { suit: Suit::Club, value: Value::Nine } => write!(f, "{}", '🃙'),
        }
    }
}
